export const SESSION_COOKIE_NAME = 'erp_session';

export const ROLE_PERMISSIONS: Record<string, readonly string[]> = {
  Admin: ['ALL'],
  Comercial: [
    '/dashboard',
    '/control_horario',
    '/presupuestos/todos',
    '/presupuestos/*',
    '/calendario/*',
    '/materiales/*',
    '/perfil',
  ],
  Administracion: [
    '/dashboard',
    '/control_horario',
    '/presupuestos/todos',
    '/presupuestos/*',
    '/calendario/*',
    '/materiales/*',
    '/recursos/unidades_moviles',
    '/certificados',
    '/certificados/*',
    '/certificados_emitidos',
    '/perfil',
    '/recursos/confirmaciones',
  ],
  Logistica: [
    '/dashboard',
    '/control_horario',
    '/presupuestos/todos',
    '/presupuestos/*',
    '/calendario/*',
    '/materiales/*',
    '/recursos/unidades_moviles',
    '/recursos/salas',
    '/perfil',
    '/recursos/confirmaciones',
  ],
  People: [
    '/dashboard',
    '/control_horario',
    '/presupuestos/todos',
    '/presupuestos/*',
    '/calendario/*',
    '/materiales/*',
    '/recursos/formadores_bomberos',
    '/perfil',
    '/recursos/confirmaciones',
  ],
  Formador: ['/usuarios/trainer/*', '/perfil', '/perfil/control_horas', '/control_horario'],
};

export const DEFAULT_ROUTE_ORDER = [
  '/usuarios/trainer/dashboard',
  '/usuarios/trainer/sesiones',
  '/usuarios/trainer/calendario',
  '/usuarios/trainer/informes',
  '/usuarios/trainer/informes/informes',
  '/usuarios/trainer/informes/formacion',
  '/usuarios/trainer/informes/preventivo',
  '/usuarios/trainer/informes/simulacro',
  '/usuarios/trainer/informes/recurso_preventivo_ebro',
  '/dashboard',
  '/control_horario',
  '/presupuestos/todos',
  '/recursos/formadores_bomberos',
  '/recursos/unidades_moviles',
  '/recursos/salas',
  '/recursos/confirmaciones',
  '/recursos/mailchimp',
  '/certificados',
  '/certificados_emitidos',
  '/certificados/templates_certificados',
  '/calendario/por_sesiones',
  '/calendario/por_formador',
  '/calendario/planificacion',
  '/calendario/disponibilidad',
  '/calendario/por_empresa',
  '/calendario/por_unidad_movil',
  '/informes/listado',
  '/informes/formacion',
  '/informes/preventivo',
  '/informes/simulacro',
  '/informes/recurso_preventivo_ebro',
  '/reporting/logs',
  '/reporting/control_horario',
  '/reporting/control_horas_formadores',
  '/usuarios/costes_extra',
  '/usuarios/nominas_formadores_externos',
  '/perfil/control_horas',
  '/reporting/webhooks_pipedrive',
  '/reporting/comparativa',
  '/usuarios',
] as const;
