ALTER TABLE deal_files
    ADD COLUMN IF NOT EXISTS author_id TEXT,
    ADD COLUMN IF NOT EXISTS author_name TEXT;

ALTER TABLE trainer_documents
    ADD COLUMN IF NOT EXISTS uploaded_by_id VARCHAR(191),
    ADD COLUMN IF NOT EXISTS uploaded_by_name VARCHAR(255);

ALTER TABLE sesion_files
    ADD COLUMN IF NOT EXISTS uploaded_by_id VARCHAR(191),
    ADD COLUMN IF NOT EXISTS uploaded_by_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS trainer_expense BOOLEAN NOT NULL DEFAULT FALSE;
